#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$app = new Symfony\Component\Console\Application('Speedwork Homestead', '3.0.2');

$app->add(new Speedwork\Homestead\MakeCommand);

$app->run();
